[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/kevinburke/go-simple-metrics"
  version = "1.0"

[[constraint]]
  name = "github.com/kevinburke/go-types"
  version = "1.2"

[[constraint]]
  name = "github.com/kevinburke/rest"
  version = "2.4"

[[constraint]]
  name = "github.com/kevinburke/handlers"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"
